# Generated by Django 5.0.2 on 2024-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='vat',
        ),
        migrations.AddField(
            model_name='supplier',
            name='reg_no',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
