# Generated by Django 5.0 on 2024-01-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='stock',
        ),
        migrations.DeleteModel(
            name='SaleBillDetails',
        ),
        migrations.DeleteModel(
            name='SaleBill',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
