# Generated by Django 5.0 on 2024-01-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_saleitem_billno_remove_saleitem_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='gstin',
            new_name='vat',
        ),
    ]
