# Generated by Django 5.0.3 on 2024-05-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
    ]
