# Generated by Django 5.0.3 on 2024-05-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_latitude_remove_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
