# Generated by Django 5.0.3 on 2024-04-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='inventory',
            new_name='name',
        ),
    ]
