# Generated by Django 5.0 on 2023-12-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountantPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_records', 'Manage records'), ('add_record', 'Add record'), ('update_record', 'Update records')),
            },
        ),
        migrations.CreateModel(
            name='CustomerPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_cart', 'Can view cart'), ('add_to_cart', 'Can add items to cart'), ('remove_from_cart', 'Can remove items from cart'), ('update_cart', 'Can update cart'), ('clear_cart', 'Can clear cart'), ('checkout', 'Can proceed to checkout'), ('view_order_history', 'Can view order history'), ('view_product_details', 'Can view product details')),
            },
        ),
        migrations.CreateModel(
            name='StaffPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_dashboard', 'Can view dashboard'), ('manage_orders', 'Can manage orders'), ('manage_products', 'Can manage products'), ('view_products', 'Manage products'), ('view_inventory', 'Manage inventory')),
            },
        ),
        migrations.CreateModel(
            name='SupplierPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_inventory', 'Manage inventory'), ('add_products', 'Add products to inventory')),
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('accountant', 'Accountant'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
