# Generated by Django 5.0 on 2023-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=100)),
                ('Cost_Per_Item', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Quantity_In_Stock', models.IntegerField()),
                ('Quantity_Sold', models.IntegerField()),
                ('Sales', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Stock_Date', models.DateField(auto_now_add=True)),
                ('Last_Sales_Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
