# Generated by Django 5.0 on 2023-12-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountantpermissions_customerpermissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_document',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
    ]
