# Generated by Django 5.0.3 on 2024-03-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rating_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='test',
            new_name='text',
        ),
    ]
