# Generated by Django 5.0 on 2023-12-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Cost_Per_Item',
            new_name='cost_per_item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Last_Sales_Date',
            new_name='last_sales_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Quantity_In_Stock',
            new_name='quantity_in_stock',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Quantity_Sold',
            new_name='quantity_sold',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Sales',
            new_name='sales',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Stock_Date',
            new_name='stock_date',
        ),
    ]
