# Generated by Django 5.0.3 on 2024-04-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_inventory_testimonial_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
    ]
