# Generated by Django 5.0.2 on 2024-03-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='receive_marketing_emails',
            field=models.BooleanField(default=True),
        ),
    ]
