# Generated by Django 5.0 on 2023-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountantpermissions_customerpermissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
