# Generated by Django 5.0.3 on 2024-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_inventory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_catalogs/'),
        ),
    ]
