# Generated by Django 5.0.3 on 2024-04-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_catalog_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='file',
            new_name='catalog_file',
        ),
    ]
