# Generated by Django 5.0 on 2023-12-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_inventory_is_deleted'),
        ('accounts', '0004_cart_orderamount'),
    ]

    operations = [
    ]
