# Generated by Django 5.0.3 on 2024-04-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_file_catalog_catalog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
