# Generated by Django 5.0.3 on 2024-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_inventory_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catalog_images',
            field=models.FileField(blank=True, null=True, upload_to='catalog_images//'),
        ),
    ]
