# Generated by Django 5.0.1 on 2024-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customerorderhistory_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart_records',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorderhistory',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderamount',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
