# Generated by Django 5.0.1 on 2024-02-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_cart_customer_alter_cart_records_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='cart_records',
        ),
        migrations.DeleteModel(
            name='customerOrderHistory',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAmount',
        ),
    ]
