# Generated by Django 5.0 on 2023-12-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_0003_inventory_is_deleted_0004_cart_orderamount'),
        ('accounts', '0007_alter_invoice_order_alter_invoice_total_amount'),
    ]

    operations = [
    ]
