# Generated by Django 5.0 on 2023-12-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
