# Generated by Django 5.0 on 2023-12-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cart_records_customerorderhistory_order_amount_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_records',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
