# Generated by Django 5.0 on 2023-12-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cart_records_total_amount_invoice_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderhistory',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
