# Generated by Django 5.0 on 2023-12-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customerorderhistory_customer'),
        ('accounts', '0013_salesdata_product'),
    ]

    operations = [
    ]
