# Generated by Django 5.0 on 2023-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20231221_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
