# Generated by Django 5.0 on 2023-12-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_inventory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderamount',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
