# Generated by Django 5.0 on 2023-12-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_cart_customer_orderamount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_records',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
