# Generated by Django 5.0 on 2024-01-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20231222_0808'),
        ('accounts', '0017_cart_records_customer'),
    ]

    operations = [
    ]
