# Generated by Django 5.0 on 2024-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20240110_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_count',
            field=models.IntegerField(null=True),
        ),
    ]
