# Generated by Django 5.0 on 2024-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cart_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_count',
        ),
        migrations.AddField(
            model_name='orderamount',
            name='cart_count',
            field=models.IntegerField(null=True),
        ),
    ]
