# Generated by Django 5.0 on 2024-01-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_cart_cart_count_orderamount_cart_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
