# Generated by Django 5.0 on 2024-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_cart_cart_count_orderamount_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
