# Generated by Django 5.0 on 2024-01-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
    ]
