# Generated by Django 5.0 on 2024-01-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
