# Generated by Django 5.0.1 on 2024-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proof/'),
        ),
    ]
