# Generated by Django 5.0.3 on 2024-03-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staffpermissions_options_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.catalog'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
