# Generated by Django 5.0.1 on 2024-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('debit/credit_card', 'Debit/Credit Card'), ('cash_deposit', 'Cash Deposit')], default='', max_length=20),
        ),
    ]
