# Generated by Django 5.0.3 on 2024-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoice_supplier_info_order_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
