# Generated by Django 5.0.1 on 2024-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Debit/Credit card', 'Debit/Credit Card'), ('Cash Deposit', 'Cash Deposit')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
