# Generated by Django 5.0.3 on 2024-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_invoice_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='catalog',
            field=models.IntegerField(null=True),
        ),
    ]
