# Generated by Django 5.0.3 on 2024-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_catalog_id_order_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
