# Generated by Django 5.0.3 on 2024-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catalog',
            field=models.CharField(default='', max_length=100),
        ),
    ]
