# Generated by Django 5.0.3 on 2024-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cart_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='catalog',
            field=models.IntegerField(null=True),
        ),
    ]
