# Generated by Django 5.0.1 on 2024-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
