# Generated by Django 5.0.1 on 2024-02-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderhistory',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerorderhistory',
            name='payment_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
