# Generated by Django 5.0.3 on 2024-03-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cart_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='catalog',
            field=models.IntegerField(null=True),
        ),
    ]
