# Generated by Django 5.0.3 on 2024-03-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_supplier_alter_order_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderhistory',
            name='catalog',
            field=models.IntegerField(null=True),
        ),
    ]
