# Generated by Django 5.0.1 on 2024-02-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_status'),
        ('orders', '0008_invoice_invoice_no_alter_invoice_order_and_more'),
    ]

    operations = [
    ]
